# numpy lesson

***triple star for italic and bold both***

In [1]:
import numpy as np

In [2]:
a = np.array([3,6,7], np.int16)

In [3]:
a

array([3, 6, 7], dtype=int16)

In [4]:
a[2]

7

In [5]:
a[1]= 9

In [6]:
a

array([3, 9, 7], dtype=int16)

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b.dtype

dtype('int32')

In [10]:
b.shape

(3, 3)

In [11]:
b.size

9

In [12]:
zeros = np.zeros((2,4))

In [13]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
c = np.arange(10)

In [15]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
lspace = np.linspace(1,5,10)

In [17]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
emp = np.empty((2,3))

In [19]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
emp_like = np.empty_like(lspace)

In [21]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
iden = np.identity(4)

In [23]:
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
emp_like.reshape((5,2))

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [25]:
emp_like.ravel()

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
ar = np.array(d)

In [28]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
ar.sum(axis = 0)

array([12, 15, 18])

In [30]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
ar.flat

In [32]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [33]:
ar.ndim

2

In [34]:
ar.nbytes

36

In [35]:
one = np.array([2,40,5,3])

In [36]:
one.argmax()

1

In [37]:
one.argsort()

array([0, 3, 2, 1], dtype=int64)

In [38]:
ar.argmax(axis = 0)

array([2, 2, 2], dtype=int64)

In [39]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
ar2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [41]:
ar+ar2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [42]:
ar.dot(ar2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [43]:
ar*ar2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [44]:
np.sqrt(ar2)

array([[3.        , 2.82842712, 2.64575131],
       [2.44948974, 2.23606798, 2.        ],
       [1.73205081, 1.41421356, 1.        ]])

In [45]:
ar2.sum()

45

In [46]:
ar2.min()

1

In [47]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [48]:
np.count_nonzero(ar2)

9

In [49]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [50]:
import sys

In [51]:
py_ar = [1,2,3,4]

In [52]:
np_ar = np.array(py_ar)

In [53]:
sys.getsizeof(1)*len(py_ar)

112

In [54]:
np_ar.itemsize* np_ar.size

16

In [55]:
np_ar.tolist()

[1, 2, 3, 4]

In [56]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [57]:
num = np.eye(3)

In [58]:
num

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
num = np.eye(3,4)
num

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [60]:
aee = np.diag([1,2,3,4])
aee

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [61]:
rand_arr = np.random.randint(5)
rand_arr

0

In [62]:
rand_arr = np.random.randint(5,10,3)
rand_arr

array([9, 9, 9])

In [63]:
rand_arr = np.random.rand(5)
rand_arr

array([0.02195471, 0.60849356, 0.20894105, 0.06025059, 0.29936819])

In [64]:
rand_arr = np.random.randn(4)
rand_arr

array([ 0.17287253,  0.02451144,  0.64149165, -0.70241492])

In [65]:
rand_arr = np.random.randn(40)
np.mean(rand_arr)

0.0841561309554998

In [66]:
nums = np.arange(10)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
nums.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
np.random.seed(12)
arrr = np.random.randint(1,111,10)
arrr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [69]:
arrr[2:6]

array([ 7,  3,  4, 68])

In [70]:
arrr[::-1]

array([50, 23, 49, 77, 68,  4,  3,  7, 28, 76])

In [71]:
arrr[:3] = 0
arrr

array([ 0,  0,  0,  3,  4, 68, 77, 49, 23, 50])

In [72]:
x = np.array([[1,3,5],[6,2,9],[8,4,7]])
x

array([[1, 3, 5],
       [6, 2, 9],
       [8, 4, 7]])

In [73]:
x[0:2,0:2]

array([[1, 3],
       [6, 2]])

In [74]:
x[1:,1:]

array([[2, 9],
       [4, 7]])

In [75]:
y = np.array([2,5,6,3,8])

In [76]:
slice = y[1:4]
slice

array([5, 6, 3])

In [77]:
slice[:]=0

In [78]:
y

array([2, 0, 0, 0, 8])

In [79]:
z = np.array([2,3,4,5,6])

In [80]:
slice1= z[1:4].copy()
slice1

array([3, 4, 5])

In [81]:
slice1[:]=0
slice1

array([0, 0, 0])

In [82]:
z

array([2, 3, 4, 5, 6])

In [83]:
z>5

array([False, False, False, False,  True])

In [84]:
v = z>5
z[v]

array([6])

In [85]:
z[z>4]

array([5, 6])

In [86]:
z[z%2==0]=0
z

array([0, 3, 0, 5, 0])

In [87]:
z/0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, nan, inf, nan])

In [88]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [89]:
a1+a2

array([ 6,  8, 10, 12])

In [90]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [91]:
np.sin(a1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [92]:
a3 = np.array([1,5,0,4])
np.array(a3,dtype='bool')

array([ True,  True, False,  True])

In [93]:
for i in a3:
    print(i)

1
5
0
4


In [94]:
a3.cumsum()

array([ 1,  6,  6, 10], dtype=int32)

In [95]:
a4 = np.array([[1,2,4],[5,6,7],[4,3,8]])

In [96]:
a4

array([[1, 2, 4],
       [5, 6, 7],
       [4, 3, 8]])

In [97]:
np.cumsum(a4,axis = 0)

array([[ 1,  2,  4],
       [ 6,  8, 11],
       [10, 11, 19]], dtype=int32)

In [98]:
np.product(a4,axis=1)

array([  8, 210,  96])

In [99]:
np.random.shuffle(a4)
a4

array([[4, 3, 8],
       [5, 6, 7],
       [1, 2, 4]])

In [100]:
np.unique(a4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
np.unique(a4).size

8

In [102]:
np.unique(a4,return_index=True, return_counts= True)

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([6, 7, 1, 0, 3, 4, 5, 2], dtype=int64),
 array([1, 1, 1, 2, 1, 1, 1, 1], dtype=int64))

In [103]:
np.random.seed(123)
random1 = np.random.randint(1,20,9).reshape(3,3)
random2 = np.random.randint(20,40,9).reshape(3,3)

In [104]:
random1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [105]:
random2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [106]:
np.hstack((random1,random2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [107]:
np.vstack((random1,random2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [108]:
fives = np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [109]:
rand = np.random.rand(4,5)
rand

array([[0.39804426, 0.73799541, 0.18249173, 0.17545176, 0.53155137],
       [0.53182759, 0.63440096, 0.84943179, 0.72445532, 0.61102351],
       [0.72244338, 0.32295891, 0.36178866, 0.22826323, 0.29371405],
       [0.63097612, 0.09210494, 0.43370117, 0.43086276, 0.4936851 ]])

In [110]:
np.random.seed(123)
arr3 = np.random.randint(1,50,20)
arr3[arr3%2==0]=-1
arr3

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

### numpy is faster than python list(timeit)

In [111]:
%timeit 2+3

17.4 ns ± 0.273 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [112]:
%timeit [i**2 for i in range(1,4)]

3.03 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [113]:
%%timeit
l = []
for i in range(1,4):
    l.append(i**2)

3.01 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [114]:
%timeit np.arange(1,4)**2

3.02 µs ± 60.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [115]:
%timeit np.arange(1,10)**2

3.2 µs ± 151 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
%timeit np.arange(1,10000)**2

35.4 µs ± 774 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [117]:
%timeit [i**2 for i in range(1,10)]

7.28 µs ± 33.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [118]:
%timeit [i**2 for i in range(1,10000)]

7.78 ms ± 32 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
